---
# tasks file for win_ad_install
- name: Install the AD-Domain-Services feature
  win_feature:
       name: AD-Domain-Services
       include_management_tools: yes
       include_sub_features: yes
       state: present

- name: Set up the AD Controller
  win_domain:
      dns_domain_name: "{{ ad_domain_name }}"
      safe_mode_password: "{{ ad_safe_mode_password }}"
  register: domain_result

- name: Reboot windows
  win_reboot:
       reboot_timeout_sec: 3600
  when: domain_result.reboot_required

- name: Print out the domain list
  win_shell: nltest /dclist:"{{ ad_domain_name }}" 
  register: shell_result

- name: output message
  debug:
     var: shell_result
